#!/usr/bin/env bash
# Build AIMHub_documentation.pdf (platex + pbibtex + dvipdfmx).
# The title shows the AIM/Hub model version: when the documentation is
# checked out as the doc/ submodule of AIM/Hub, version.tex is regenerated
# from ../define/version.gms; otherwise the committed version.tex is used.
filename=AIMHub_documentation
echo ${filename}

if [ -f ../define/version.gms ]; then
  version=$(sed -n 's/^\$setglobal AIMHub_version \([^ ]*\).*/\1/p' ../define/version.gms)
  if [ -n "$version" ]; then
    {
      printf '%s\n' '% Generated by tex.sh from ../define/version.gms. Do not edit by hand.'
      printf '%s\n' '\newcommand{\AIMHubVersion}{'"$version"'}'
    } > version.tex
    echo "AIM/Hub version: $version"
  fi
fi

rm -f ${filename}.aux ${filename}.bbl ${filename}.blg ${filename}.dvi ${filename}.lof
extractbb fig/*.png fig/*.jpg 2>/dev/null
platex ${filename}.tex
pbibtex ${filename}
platex ${filename}.tex
platex ${filename}.tex

dvipdfmx -f ptex-ipa.map ${filename}
rm -f fig/*.xbb
read -p "press any key to finish"
